export const FETCH_PERFUMES = "FETCH_PERFUMES";
export const FETCH_PERFUME = "FETCH_PERFUME";
export const FETCH_PERFUMES_BY_FILTER_PARAMS = "FETCH_PERFUMES_BY_FILTER_PARAMS";
export const FETCH_PERFUMES_BY_GENDER = "FETCH_PERFUMES_BY_GENDER";
export const FETCH_PERFUMES_BY_PERFUMER = "FETCH_PERFUMES_BY_PERFUMER";

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const LOADING_CART = "LOADING_CART";
export const PERFUME_ADDED_TO_CART_SUCCESS = "PERFUME_ADDED_TO_CART_SUCCESS";
export const PERFUME_REMOVED_FROM_CART_SUCCESS = "PERFUME_REMOVED_FROM_CART_SUCCESS";

export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ALL_USERS_ORDERS_SUCCESS = "FETCH_ALL_USERS_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS_SUCCESS = "FETCH_ALL_ORDERS_SUCCESS";
export const ORDER_ADDED_SUCCESS = "ORDER_ADDED_SUCCESS";
export const ORDER_ADDED_FAILURE = "ORDER_ADDED_FAILURE";
export const ORDER_CONFIRMED_SUCCESS = "ORDER_CONFIRMED_SUCCESS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAILURE = "PASSWORD_RESET_FAILURE";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const ACTIVATE_ACCOUNT_SUCCESS = "ACTIVATE_ACCOUNT_SUCCESS";
export const ACTIVATE_ACCOUNT_FAILURE = "ACTIVATE_ACCOUNT_FAILURE";
export const RESET_PASSWORD_CODE_SUCCESS = "RESET_PASSWORD_CODE_SUCCESS";
export const RESET_PASSWORD_CODE_FAILURE = "RESET_PASSWORD_CODE_FAILURE";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const FORM_RESET = "FORM_RESET";

export const PERFUME_ADDED_SUCCESS = "PERFUME_ADDED_SUCCESS";
export const PERFUME_UPDATED_SUCCESS = "PERFUME_UPDATED_SUCCESS";
export const PERFUME_ADDED_FAILURE = "PERFUME_ADDED_FAILURE";
export const PERFUME_UPDATED_FAILURE = "PERFUME_UPDATED_FAILURE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";

export const USER_UPDATED_SUCCESS = "USER_UPDATED_SUCCESS";
export const USER_ADDED_REVIEW_SUCCESS = "USER_ADDED_REVIEW_SUCCESS";
export const USER_ADDED_REVIEW_FAILURE = "USER_ADDED_REVIEW_FAILURE";

