export const FETCH_PERFUMES = "FETCH_PERFUMES";
export const FETCH_PERFUME = "FETCH_PERFUME";
export const FETCH_PERFUMES_BY_FILTER_PARAMS = "FETCH_PERFUMES_BY_FILTER_PARAMS";
export const FETCH_PERFUMES_BY_GENDER = "FETCH_PERFUMES_BY_GENDER";
export const FETCH_PERFUMES_BY_PERFUMER = "FETCH_PERFUMES_BY_PERFUMER";

export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const LOADING_CART = "LOADING_CART";
export const PERFUME_ADDED_TO_CART_SUCCESS = "PERFUME_ADDED_TO_CART_SUCCESS";
export const PERFUME_REMOVED_FROM_CART_SUCCESS = "PERFUME_REMOVED_FROM_CART_SUCCESS";

export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ALL_USERS_ORDERS_SUCCESS = "FETCH_ALL_USERS_ORDERS_SUCCESS";
export const FETCH_USER_ORDERS = "FETCH_ALL_ORDERS";
export const ORDER_ADDED = "ORDER_ADDED";
export const ORDER_CONFIRMED = "ORDER_CONFIRMED";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const PERFUME_ADDED_SUCCESS = "PERFUME_ADDED_SUCCESS";
export const PERFUME_UPDATED_SUCCESS = "PERFUME_UPDATED_SUCCESS";
export const PERFUME_ADDED_FAILURE = "PERFUME_ADDED_FAILURE";
export const PERFUME_UPDATED_FAILURE = "PERFUME_UPDATED_FAILURE";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_ALL_USERS_SUCCESS = "FETCH_ALL_USERS_SUCCESS";
export const USER_UPDATED_SUCCESS = "USER_UPDATED_SUCCESS";
