INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (1, 'Germany', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/4735a4c8-e1fc-43ce-8ff9-0bd28d00ce20.Hugo Boss Boss Bottled Night.jpg', 'Salmwood, Musky notes, Sandalwood', 'Cardamom, Jasmine, African violet', 'Birch leaf, Lavender', 'male', 'Boss Bottled Night', 'Hugo Boss', 35, 'Eau de Toilette', '100', 20100, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (2, 'Germany', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/17d6f8a1-aa84-4823-bd18-ccb0fdbe7fe9.Hugo Boss Hugo Man.jpg', 'Moss, Sandalwood, Fir balsam', 'Carnation, Geranium leaf, Jasmine', 'Basil, Grapefruit, Green apple, Mint', 'male', 'Hugo Man', 'Hugo Boss', 21, 'Eau de Toilette', '75', 19950, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (3, 'Germany', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/ba9272ca-20af-4e41-89b7-24018be4acb1.Hugo Boss The Scent.jpg', 'Leather', 'Maninka fruit, Lavender', 'Ginger', 'male', 'The Scent', 'Hugo Boss', 45, 'Eau de Toilette', '100', 20150, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (4, 'Germany', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/540f8e7d-2259-4a20-becf-4ed5cfc2912e.Hugo Boss Boss Woman.jpg', 'Sandalwood, Cedar', 'Freesia, Violet root', 'Mandarin orange, Mango', 'female', 'Boss Woman', 'Hugo Boss', 26, 'Eau de parfum', '90', 20000, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (5, 'Germany', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/1fb6dd1b-a134-4e6f-8215-60d465d33d72.Hugo Boss Hugo Deep Red.jpg', 'Musk, Sandalwood, Vanilla', 'Freesia, Hibiscus, Ginger', 'Pear, Blood orange, Clementine', 'female', 'Deep Red', 'Hugo Boss', 27, 'Eau de parfum', '90', 20010, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (6, 'Germany', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/62e9bf9b-8fea-4eb2-9935-21e868e1b93d.Hugo Boss The Scent For Her.jpg', 'Roasted cocoa', 'Osmanthus', 'Peach, Freesia', 'female', 'The Scent For Her', 'Hugo Boss', 47, 'Eau de parfum', '100', 20160, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (26, 'Spain', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/6524de16-c086-49fe-a6e5-c9efc35f1a02.Carolina Herrera Bad Boy.jpg', 'Tonka bean, Cocoa absolute', 'Cedarwood, Sage', 'Black pepper, White pepper, Italian bergamot', 'male', 'Bad Boy', 'Carolina Herrera', 76, 'Eau de Toilette', '100', 20190, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (27, 'Spain', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/184c9da2-2445-4b01-87b8-b4f8b5f6ab8c.Carolina Herrera Good Girl.jpg', 'Roasted tonka bean, Cocoa, Sandalwood', 'Tuberose, Bulgarian rose, Jasmine sambac', 'Bergamot, Lemon', 'female', 'Good Girl', 'Carolina Herrera', 156, 'Eau de parfum', '150', 20160, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (28, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/e31f6d6c-e585-40a4-970c-f25322667924.Chanel Allure homme Sport.jpg', 'Amber, Musk, Tonka bean', 'Neroli, Pepper, Cedar', 'Aldehydes, Mandarin orange, Seawater', 'male', 'Allure homme Sport', 'Chanel', 85, 'Eau de Toilette', '100', 20040, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (29, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/ac6c7a11-97f8-44b1-9b10-f96997212dd4.Chanel Bleu de Chanel Eau de Parfum.jpg', 'Ginger, Sandalwood, Frankincense', 'Grapefruit, Labdanum, Cedar', 'Pink pepper, Vetiver, Citrus notes', 'male', 'Bleu de Chanel', 'Chanel', 88, 'Eau de parfum', '100', 20140, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (30, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/7049225c-03bb-45a7-ba6a-86274f8668b9.Chanel Egoiste Platinum.jpg', 'Amber, Oakmoss, Sandalwood', 'Galbanum, Geranium, Jasmine', 'Lavender, Neroli, Petitgrain', 'male', 'Egoiste Platinum', 'Chanel', 70, 'Eau de Toilette', '100', 19930, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (31, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/bcc4bb2a-907d-4531-9d7f-178c765c5ed3.Chanel Chance Eau Fraiche.jpg', 'Amber, Iris, Musk, Patchouli', 'Jasmine, Pink pepper, Water hyacinth', 'Cedar, Citrus fruits', 'female', 'Chance Eau Fraiche', 'Chanel', 90, 'Eau de Toilette', '100', 20070, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (32, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/2b5f80ca-e0f3-4e99-b5e4-11ccb9153b00.Chanel Gabrielle Essence.jpg', 'Sandalwood, Vanilla, White musk', 'Tuberose, Jasmine, Ylang-ylang', 'Citrus fruits, Red fruits', 'female', 'Gabrielle Essence', 'Chanel', 104, 'Eau de parfum', '100', 20190, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (33, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/4b51181b-5551-4321-b5e7-f7612584c9b2.Chanel N5.jpg', 'Amber, Sandalwood, Vanilla', 'Iris, Grasse jasmine', 'Aldehydes, Bergamot, Neroli', 'female', 'Chanel N5', 'Chanel', 192, 'Eau de parfum', '200', 19210, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (34, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/bdb203a9-0725-4ed4-a71a-db7eeb915fae.Creed Aventus.jpg', 'Ambergris, Oakmoss, Musk', 'Birch, Jasmine, Patchouli', 'Pineapple, Apple, Bergamot, Blackcurrant', 'male', 'Aventus', 'Creed', 152, 'Eau de parfum', '100', 20100, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (35, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/162cfbe2-2dc2-4271-8a63-23981a7e3cc4.Creed Bois du Portugal.jpg', 'Sandalwood, Vetiver, Ambergris', 'Cedarwood', 'Bergamot, Lavender', 'male', 'Bois du Portugal', 'Creed', 110, 'Eau de parfum', '100', 19870, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (36, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/1d428b77-0ffd-449f-bcaa-04a094b51de7.Creed Original Vetiver.jpg', 'Ambergris, Sandalwood, Musk, Vetiver', 'White pepper, Coriander, Pink pepper', 'Bergamot, Bitter orange, Mandarin orange', 'male', 'Original Vetiver', 'Creed', 97, 'Eau de parfum', '100', 20040, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (37, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/5fd3de8e-1022-47a2-ae58-a089a65bd90c.Creed Acqua Fiorentina.jpg', 'Grapefruit, Sandalwood, Cedar', 'Bergamot, Pear, Rose', 'Apple, Prune, Greengage plum', 'female', 'Acqua Fiorentina', 'Creed', 100, 'Eau de parfum', '75', 20090, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (38, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/7d32f694-9cc3-4770-844a-47400e6f5c6b.Creed Aventus for Her.jpg', 'Peach, Blackcurrant, Ylang-ylang', 'Rose, Styrax, Mysore sandalwood', 'Green apple, Violet leaf, Calabrian bergamot', 'female', 'Aventus for Her', 'Creed', 141, 'Eau de parfum', '75', 20160, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (39, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/cbb8efd1-f55a-4db3-8511-f0b5b446533d.Creed Love in Black.jpg', 'Rose, Burgundy blackcurrant, Violet', 'Florentine iris, Clove', 'White violet', 'female', 'Love in Black', 'Creed', 89, 'Eau de parfum', '75', 20080, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (40, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/0f0acb70-dc64-474f-878a-1b214d250d94.CreedLoveinWhite.jpg', 'Ambergris, Mysore sandalwood, Vanilla', 'Florentine iris, Yellow narcissus, Magnolia', 'Orange zest', 'female', 'Love in White', 'Creed', 94, 'Eau de parfum', '75', 20050, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (41, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/0158183f-2412-4c61-a962-7c96e43c19c3.Dior Fahrenheit.jpg', 'Amber, Leather, Musk', 'Carnation, Honeysuckle, Jasmine', 'Bergamot, Camomile, Lavender, Mandarin orange', 'male', 'Fahrenheit', 'Dior', 62, 'Eau de Toilette', '100', 19880, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (42, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/27f0b3d3-2634-4e74-971a-f780c4480482.Dior Homme.jpg', 'Virginia cedar', 'Ecuadorian ambrette seed', 'Florentine iris absolute', 'male', 'Homme', 'Dior', 90, 'Eau de parfum', '100', 20070, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (43, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/03e65b3b-7b1f-400c-9bb8-a8956bdaa4be.Dior Sauvage.jpg', 'Ambroxan', 'Bergamot', 'Sichuan Pepper', 'male', 'Sauvage', 'Dior', 62, 'Eau de Toilette', '100', 20150, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (44, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/94c85cfd-f090-4d49-b2e9-dcff34eec8c1.Dior Jadore.jpg', 'Vanilla, Cedar, Musk', 'Lily of the valley, Rose, Violet', 'Bergamot, Pear, Melon, Peach', 'female', 'Jadore', 'Dior', 81, 'Eau de parfum', '100', 19990, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (45, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/85f8de21-24d5-473b-8d63-6ba6c2d4d25e.Dior Miss Dior.jpg', 'Ambergris, Musk, Patchouli', 'Jasmine, Caramel, Popcorn', 'Pineapple, Cherry, Mandarin orange', 'female', 'Miss Dior', 'Dior', 90, 'Eau de parfum', '100', 20110, 0);
INSERT INTO perfume (id, country, description, filename, fragrance_base_notes, fragrance_middle_notes, fragrance_top_notes, perfume_gender, perfume_title, perfumer, price, type, volume, year, perfume_rating) VALUES (46, 'France', null, 'https://perfumeswebstorage.s3.eu-central-1.amazonaws.com/63534821-1eb9-4b44-afd3-61c3b8ca4a25.Dior Poison Girl.jpg', 'Venezuelan tonka bean', 'Grasse rose', 'Bitter orange', 'female', 'Poison Girl', 'Dior', 75, 'Eau de parfum', '100', 20160, 0);

INSERT INTO review (id, author, date, message, rating) VALUES (123, 'John', '2021-02-07', 'Hello world', 5);
INSERT INTO review (id, author, date, message, rating) VALUES (124, 'John2', '2021-02-07', 'Hello world2', 4);

INSERT INTO perfume_reviews (perfume_id, reviews_id) VALUES (2, 123);
INSERT INTO perfume_reviews (perfume_id, reviews_id) VALUES (2, 124);


