create sequence hibernate_sequence start 122 increment 1;

create table orders (
    id int8 generated by default as identity,
    address varchar(255),
    city varchar(255),
    date date,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    phone_number varchar(255),
    post_index int4 not null check (post_index>=5),
    total_price float8,
    user_id int8,
    primary key (id)
);

create table orders_perfume_list (
    order_id int8 not null,
    perfume_list_id int8 not null,
    perfume_list_order int4 not null,
    primary key (order_id, perfume_list_order)
);

create table perfume (
    id int8 not null,
    country varchar(255),
    description varchar(255),
    filename varchar(255),
    fragrance_base_notes varchar(255),
    fragrance_middle_notes varchar(255),
    fragrance_top_notes varchar(255),
    perfume_gender varchar(255),
    perfume_title varchar(255),
    perfumer varchar(255),
    price int4 not null,
    type varchar(255),
    volume varchar(255),
    year int4 not null,
    primary key (id)
);

create table user_role (
    user_id int8 not null,
    roles varchar(255)
);

create table usr (
    id int8 not null,
    activation_code varchar(255),
    active boolean not null,
    email varchar(255),
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

create table usr_perfume_list (
    user_id int8 not null,
    perfume_list_id int8 not null
);

alter table if exists orders
    add constraint FK7ncuqw9n77odylknbo8aikc9w
    foreign key (user_id) references usr;

alter table if exists orders_perfume_list
    add constraint FKi6hpa14qaenek8pc9pf3vmlei
    foreign key (perfume_list_id) references perfume;

alter table if exists orders_perfume_list
    add constraint FK8jft4d30d5dgvauht7ssndwau
    foreign key (order_id) references orders;

alter table if exists user_role
    add constraint FKfpm8swft53ulq2hl11yplpr5
    foreign key (user_id) references usr;

alter table if exists usr_perfume_list
    add constraint FK1n7n8prjoexkp1twc9f6kgbtm
    foreign key (perfume_list_id) references perfume;

alter table if exists usr_perfume_list
    add constraint FKc5b4lo20noteewtlrq1kd8nhs
    foreign key (user_id) references usr;
